# Generated by Django 3.2.9 on 2021-12-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discount', models.IntegerField(null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(default=0, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/img/')),
                ('disable', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='WaistAndColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=255, null=True)),
                ('stock_s', models.IntegerField(blank=True, null=True)),
                ('stock_m', models.IntegerField(blank=True, null=True)),
                ('stock_l', models.IntegerField(blank=True, null=True)),
                ('stock_xl', models.IntegerField(blank=True, null=True)),
                ('stock_xxl', models.IntegerField(blank=True, null=True)),
                ('stock_xxxl', models.IntegerField(blank=True, null=True)),
                ('stock_for_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Waist and color',
                'verbose_name_plural': 'Waists and colors',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='products.WaistAndColor'),
        ),
        migrations.AddField(
            model_name='product',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.event'),
        ),
    ]
