# Generated by Django 3.2.9 on 2021-12-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discount', models.IntegerField(null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Waist',
            fields=[
                ('id_waist', models.AutoField(primary_key=True, serialize=False)),
                ('stock_s', models.IntegerField(blank=True, null=True)),
                ('stock_m', models.IntegerField(blank=True, null=True)),
                ('stock_l', models.IntegerField(blank=True, null=True)),
                ('stock_xl', models.IntegerField(blank=True, null=True)),
                ('stock_xxl', models.IntegerField(blank=True, null=True)),
                ('stock_xxxl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'waist',
                'verbose_name_plural': 'waists',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(default=0, max_length=255, null=True)),
                ('disable', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.event')),
                ('ids_colors', models.ManyToManyField(blank=True, to='products.Colors')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.AddField(
            model_name='colors',
            name='id_talle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.waist'),
        ),
    ]
