# Generated by Django 3.2.9 on 2021-12-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Waist and color',
                'verbose_name_plural': 'Waists and colors',
            },
        ),
        migrations.CreateModel(
            name='Waist',
            fields=[
                ('id_waist', models.AutoField(primary_key=True, serialize=False)),
                ('stock_s', models.IntegerField(blank=True, null=True)),
                ('stock_m', models.IntegerField(blank=True, null=True)),
                ('stock_l', models.IntegerField(blank=True, null=True)),
                ('stock_xl', models.IntegerField(blank=True, null=True)),
                ('stock_xxl', models.IntegerField(blank=True, null=True)),
                ('stock_xxxl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'waist',
                'verbose_name_plural': 'waists',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.DeleteModel(
            name='WaistAndColor',
        ),
        migrations.AddField(
            model_name='colors',
            name='id_talle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.waist'),
        ),
        migrations.AddField(
            model_name='product',
            name='ids_colors',
            field=models.ManyToManyField(blank=True, to='products.Colors'),
        ),
    ]
