# Generated by Django 3.2.9 on 2021-12-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id_cart', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=255)),
                ('waist', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='ShoppingHistory',
            fields=[
                ('id_history', models.AutoField(primary_key=True, serialize=False)),
                ('date_purchase', models.DateField(auto_now_add=True)),
                ('color', models.CharField(max_length=255)),
                ('waist', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
