# Generated by Django 3.2.9 on 2021-12-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211216_1320'),
        ('mod', '0003_alter_pendingshipments_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingshipments',
            name='product',
            field=models.ForeignKey(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001C797AFAE00>', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product'),
        ),
    ]
