# Generated by Django 3.2.9 on 2021-12-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
        ('mod', '0006_alter_pendingshipments_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingshipments',
            name='product',
            field=models.ForeignKey(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000021D6E901FF0>', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product'),
        ),
    ]
