# Generated by Django 3.2.9 on 2021-12-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211217_1339'),
        ('mod', '0008_alter_pendingshipments_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingshipments',
            name='product',
            field=models.ForeignKey(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000025E43272020>', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product'),
        ),
    ]
